### ISSUE TITLE
build_option::optimize_data

### ISSUE THREAD

**Issue by Daniel-01** [intel/clDNN#19]
Hi,
This unit test worked fine with Drop 3.0 but doesn't work with Drop 5.0.
If I remove the optimize_data build option it works on Drop 5.0 too.
I don't know if this is a problem with my test or with clDNN.

[test.zip](https://github.com/intel/clDNN/files/1475036/test.zip)

I am running this test on Core i3-6100.

**Comment by tponieck** [comment]
Hi Daniel,
unfortunately I have classic answer: "it works with my environment" only (both with and without optimize_data param), Can you share more details of your setup and output log from your run?
Driver, OS, if it is Linux - installed patches, memory size and speed. 
thanks 
tponieck

**Comment by Daniel-01** [comment]
Windows 10.
Visual Studio 2015 Update 3.
Intel HD Graphics 530 driver version 21.20.16.4627.

**Comment by Daniel-01** [comment]
I expect the output to be same as the input:

1  2  3  4
5  6  7  8
9 10 11 12

13 14 15 16
17 18 19 20
21 22 23 24

But I get:

1 0 0 0
5 0 0 0
9 5.60519e-45 5.60519e-45 5.60519e-45

13 0 0 0
17 0 0 0
21 0 0 0

**Comment by tponieck** [comment]
Could you update your driver to the one from our read me please?
https://downloadcenter.intel.com/download/26941

**Comment by Daniel-01** [comment]
I have not been able to install that driver on my HP computer. I have tried both the exe and the zip and doing "update driver" from device manager, but I cannot get it to upgrade. I have tried uninstalling the current driver, but it just reinstalls it again.
I dont have access to any other compatible computer today, but I can try on another computer on monday.

**Comment by Daniel-01** [comment]
I tried it on a i5-6500 with driver version 22.20.16.4729 and it worked fine.
So it is probably a driver issue.

**Comment by tponieck** [comment]
Thanks for confirmation
regards,
tomek
