### ISSUE TITLE
deconvolution is very slow

### ISSUE THREAD

**Issue by Daniel-01** [intel/clDNN#20]
I think the prediction speed of clDNN is generally very good and it outperforms MKL on the same 
processor for many operations I have tested. But the deconvolution operation seem to be very slow. 
On Core i3-6100 and i5-6500 deconvolution takes approximately 40-50 times longer with clDNN than MKL in my tests. That is such a big difference that I don't think it is caused simply by lack of optimization.

See attached test case for details of how I measured it.
[speed.zip](https://github.com/intel/clDNN/files/1481377/speed.zip)

**Comment by tponieck** [comment]
Hi Daniel, 
Thanks for pointing this out. We are aware of this low performance because our deconvolution implementation is very naïve, and this is the reason why it is so slow.  There is a plan to improve deconvolution kernel in future. 
tponieck
