### ISSUE TITLE
cmake -DCMAKE_BUILD_TYPE=Release .. Error 

### ISSUE THREAD

**Issue by Jia-HongHenryLee** [intel/clDNN#23]
Hello,
    My OS is Ubuntu 16.04.
    cmake version is 3.7.2.
    intel graphic driver is  SRB5
    intel opencl sdk is 1.2-7.0
    When i run cmake -DCMAKE_BUILD_TYPE=Release .., i get this following error:
   **-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
[clDNN] CLDNN__ARCHITECTURE_TARGET: Target architecture is not specified. Trying to deduce it from context.
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.12", minimum required is "2.7") 
CMake Warning at /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version 106400
Call Stack (most recent call first):
  /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:1454 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:596 (find_package)

CMake Warning at /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version 106400
Call Stack (most recent call first):
  /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:1454 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:596 (find_package)

CMake Warning at /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version 106400
Call Stack (most recent call first):
  /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:1454 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:596 (find_package)

CMake Warning at /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version 106400
Call Stack (most recent call first):
  /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:1454 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:596 (find_package)

-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   system
--   date_time
--   program_options
--   filesystem
-- [clDNN] ======================== clDNN Project =======================
-- [clDNN] Version:          1.3.8.0
-- [clDNN]
-- [clDNN] Build type:       Release (for single-configuration generators)
-- [clDNN] Av. build types:  Debug;Release (for multi-configuration generators)
-- [clDNN]
-- [clDNN] Output bin directory:
-- [clDNN]  - "/home/user1/cldnn/build/out/Linux64/Release"
-- [clDNN] Output lib directory:
-- [clDNN]  - "/home/user1/cldnn/build/out/Linux64/Release"
-- [clDNN] Architecture:
-- [clDNN]  - target: Linux64    (detected: Linux64)
-- [clDNN]
-- [clDNN]
-- [clDNN] Advanced:
-- [clDNN]  - ICD version used to build:     6.3
-- [clDNN]  - boost ver. used to build:      1.64.0
-- [clDNN]
-- [clDNN]  - Include/Build cldnn core:      ON
-- [clDNN]  - Include/Build kernel selector: ON
-- [clDNN]  - Include/Build tests:           ON
-- [clDNN]  - Include/Build tutorial:        ON
-- [clDNN]
-- [clDNN]  - Run tests:                     OFF
-- [clDNN]
-- [clDNN]  - Use static C++ Runtime:        OFF
-- [clDNN]  - Allow unsafe size opts:        ON
-- [clDNN]  - CMake debug trace:             OFF
-- [clDNN]
-- [clDNN]
-- [clDNN] ICD:
-- [clDNN]  - Root:            /home/user1/cldnn/common/intel_ocl_icd/6.3
-- [clDNN]     + Headers:      /home/user1/cldnn/common/intel_ocl_icd/6.3/linux/include
-- [clDNN]     + Static libs:  /home/user1/cldnn/common/intel_ocl_icd/6.3/linux/Release/lib/x64
-- [clDNN]     + Shared libs:  /home/user1/cldnn/common/intel_ocl_icd/6.3/linux/Release/bin/x64
-- [clDNN]     + Libs to link: /home/user1/cldnn/common/intel_ocl_icd/6.3/linux/Release/bin/x64
-- [clDNN]
-- [clDNN] boost libraries:
-- [clDNN]  - Root:            /home/user1/cldnn/common/boost/1.64.0
-- [clDNN]     + Headers:      /home/user1/cldnn/common/boost/1.64.0/include/boost-1_64
-- [clDNN]     + Libs to link: /home/user1/cldnn/common/boost/1.64.0/linux/x64/lib
-- [clDNN] =============================================================================
-- Performing Test CLDNN__COMPILER_SUPPORTS_CXX14
-- Performing Test CLDNN__COMPILER_SUPPORTS_CXX14 - Success
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- [clDNN] Selected capabilities: public
-- Configuring done
CMake Error at src/CMakeLists.txt:191 (add_library):
  Target "clDNN_shlib" links to target "Boost::filesystem" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at src/CMakeLists.txt:191 (add_library):
  Target "clDNN_shlib" links to target "Boost::system" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at tests/CMakeLists.txt:123 (add_executable):
  Target "tests" links to target "Boost::filesystem" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at tests/CMakeLists.txt:123 (add_executable):
  Target "tests" links to target "Boost::system" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at tutorial/CMakeLists.txt:60 (add_executable):
  Target "tutorial" links to target "Boost::filesystem" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at tutorial/CMakeLists.txt:60 (add_executable):
  Target "tutorial" links to target "Boost::system" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

-- Generating done
-- Build files have been written to: /home/user1/cldnn/build**

Please help me. I cannot find any solutions. Thank you very much.

**Comment by Jia-HongHenryLee** [comment]
--------------------------
Hardware readiness checks:
--------------------------
 [ OK ] Processor name: Intel(R) Xeon(R) CPU E3-1585 v5 @ 3.50GHz
 [ INFO ] Intel Processor
 [ INFO ] Processor brand: Xeon
 [ INFO ] Processor arch: Skylake
--------------------------
OS readiness checks:
--------------------------
 [ INFO ] GPU PCI id     : 193A
 [ INFO ] GPU description: SKL SRV GT4e
 [ OK ] GPU visible to OS
 [ INFO ] no nomodeset in GRUB cmdline (good)
 [ INFO ] Linux distro   : Ubuntu 16.04
 [ INFO ] Linux kernel   : 4.13.0-32-generic
 [ INFO ] glibc version  : 2.23
 [ INFO ] Linux distro suitable for Generic install
 [ INFO ] gcc version    : 20160609 (>=4.8.2 suggested)
--------------------------
Media Server Studio Install:
--------------------------
 [ OK ] user in video group
 [ ERROR ] libva.so.1 not found.  Check LD_LIBRARY_PATH contains '/usr/lib64;/usr/local/lib'
 [ ERROR ] libva not loading Intel iHD
 [ ERROR ] vainfo not reporting codec entry points
 [ INFO ] i915 driver in use by Intel video adapter
 [ ERROR ] no libva include files.  Are Intel components installed?
--------------------------
Component Smoke Tests:
--------------------------
 [ ERROR ] no Media SDK include files.  Are Intel components installed?
 [ OK ] OpenCL check:platform:Intel(R) OpenCL GPU OK CPU OK
platform:Experimental OpenCL 2.1 CPU Only Platform GPU OK CPU OK

**Comment by mwalkowi** [comment]
Hi Jia-HongHenryLee,
The issue you are observing is connected to **too old CMake version**. Recently we updated boost we are using (to version 1.64.0) which require newer CMake (its *FindBoost* module) to correctly resolve dependencies. We strongly recommend using CMake 3.9+ now.

I have updated [README](https://github.com/intel/clDNN/blob/master/README.md#system-requirements) with new requirements. I am very sorry for inconvenience. If, for some reason, you cannot update CMake to 3.9+ you can try workaround (also described in [README](https://github.com/intel/clDNN/blob/master/README.md#system-requirements)):

> **NOTE:** In rare situation when update of CMake is not possible, you can try to update / override only *FindBoost.cmake* module. You can do that by downloading *FindBoost.cmake* file from newer version of CMake (e.g. from [here](https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/FindBoost.cmake)) and putting the file into *common/boost/cmake/modules* directory (create it if necessary). This directory will be attached
    to the list of modules if your CMake version is lower than 3.9.

Let me know if this solves your problem.

Best Wishes!

**Comment by Jia-HongHenryLee** [comment]
@mwalkowi  Thank you very much. I change the version of cmake to 3.10.2, and solve this problem.
