### ISSUE TITLE
Execute tests error

### ISSUE THREAD

**Issue by Jia-HongHenryLee** [intel/clDNN#24]
Hello,
     my environment of hardware:
[ OK ] Processor name: Intel(R) Xeon(R) CPU E3-1585 v5 @ 3.50GHz
 [ INFO ] Intel Processor
 [ INFO ] Processor brand: Xeon
 [ INFO ] Processor arch: Skylake

OS readiness checks:
 [ INFO ] GPU PCI id     : 193A
 [ INFO ] GPU description: SKL SRV GT4e
 [ OK ] GPU visible to OS
 [ INFO ] no nomodeset in GRUB cmdline (good)
 [ INFO ] Linux distro   : Ubuntu 16.04
 [ INFO ] Linux kernel   : 4.13.0-32-generic
 [ INFO ] glibc version  : 2.23
 [ INFO ] Linux distro suitable for Generic install
 [ INFO ] gcc version    : 20160609 (>=4.8.2 suggested)

Media Server Studio Install:
 [ OK ] user in video group
 [ ERROR ] libva.so.1 not found.  Check LD_LIBRARY_PATH contains '/usr/lib64;/usr/local/lib'
 [ ERROR ] libva not loading Intel iHD
 [ ERROR ] vainfo not reporting codec entry points
 [ INFO ] i915 driver in use by Intel video adapter
 [ ERROR ] no libva include files.  Are Intel components installed?

Component Smoke Tests:
 [ ERROR ] no Media SDK include files.  Are Intel components installed?
 [ OK ] OpenCL check:platform:Intel(R) OpenCL GPU OK CPU OK
platform:Experimental OpenCL 2.1 CPU Only Platform GPU OK CPU OK
     

      When I execute the tests and tutorial, i get this following error:
      terminate called after throwing an instance of 'cldnn::error'
      what():  failed to create engine: Device lookup failed - unsupported device id: 0x193A. Note: HD5xx+ 
      devices are supported
      Aborted (core dumped)  
      tests/CMakeFiles/tests.dir/build.make:904: recipe for target 'out/Linux64/Release/tests64' failed 
      make[2]: *** [out/Linux64/Release/tests64] Error 134 
      make[2]: *** Deleting file 'out/Linux64/Release/tests64'
      CMakeFiles/Makefile2:197: recipe for target 'tests/CMakeFiles/tests.dir/all' failed  
      make[1]: *** [tests/CMakeFiles/tests.dir/all] Error 2 
      Makefile:129: recipe for target 'all' failed
      make: *** [all] Error 2

Thank you very much

**Comment by Jia-HongHenryLee** [comment]
By the way, If i only want to compile example_cldnn.cpp (in tutorial folder), how to compile it? gcc example_cldnn.cpp  -o example_cldnn ?
When i see the code of example_cldnn.cpp, I find that i don't have the files, conv1_weights.bin, fc1_weights.data..etc, how to get this files?

Thank you very much

**Comment by tponieck** [comment]
Hi Jia-HongHenryLee,
We didn't have your device id in our list of supported HW's. I've added it already. Thanks for pointing it out. 
Regarding to your second question: you have to prepare your own files with data and pare it to cldnn format.

**Comment by Essenlin** [comment]
Hi tponieck,
What conv1_weights.bin and fc1_weights.data? How can i prepare for it?

**Comment by tponieck** [comment]
You need to fill memory primitive with data based on weights layout i.e.:
layout conv1_weights_layout(data_type, format::bfyx,{ conv1_out_channels, input_channels, conv_krnl_size, conv_krnl_size });
bfyx means order will be:
output featre map - input feature map - height (spatial y) - width (spatial x)
data should be float precision
to get better understanding I recommend to follow test case: basic_ofm_wsiz3x2x2x1_in2x2x1_nopad from: https://github.com/intel/clDNN/blob/master/tests/test_cases/convolution_gpu_test.cpp
