### ISSUE TITLE
Support for HD Graphics 6000?

### ISSUE THREAD

**Issue by kodonnell** [intel/clDNN#26]
Is this planned to be supported? Alternatively, what work would need to be done to support it? We're looking at the i5-5250u because the HD Graphics 6000 seems to have good GFLOPS at a good price.

**Comment by kodonnell** [comment]
If anyone's wondering, I just added my device ID to `src/caps/public/gpu_devices.inc` and the tutorial runs ... not sure if everything will.

**Comment by tponieck** [comment]
Hi Kodonnell, 
adding hw id to gpu_device.inc will enable to run your hw with cldnn, note we didn't test it on the platforms that are not on the list. You can see some conformance and performance issues, let us know how it works.

tponieck
