### ISSUE TITLE
"$ make tests" failed.

### ISSUE THREAD

**Issue by smit411** [intel/clDNN#43]
After running command "$ make tests", 8 tests are shown as failed. Also showing error:

> tests/CMakeFiles/tests.dir/build.make:867: recipe for target 'build/out/Linux64/Debug/tests64' failed
>
What could be the reason? 
Log:
> [----------] Global test environment tear-down
> [==========] 525 tests from 89 test cases ran. (151136 ms total)
> [  PASSED  ] 517 tests.
> [  FAILED  ] 8 tests, listed below:
> [  FAILED  ] convolution_grad_weights_f32_fw_gpu.basic_wsiz2x2_in2x2x1x2_bfyx_stride2_pad1_fwd_backw
> [  FAILED  ] convolution_grad_weights_f32_fw_gpu.basic_wsiz1x1_in1x2x5x5_bfyx_stride2_pad1
> [  FAILED  ] convolution_grad_weights_f32_fw_gpu.basic_wsiz2x2_in32x1x2x2_yxfb_stride1
> [  FAILED  ] memory_pool.basic_non_padded_relu_pipe
> [  FAILED  ] memory_pool.basic_non_padded_relu_and_pooling_pipe
> [  FAILED  ] memory_pool.multi_outputs_network
> [  FAILED  ] memory_pool.shared_mem_pool_same_topology_twice
> [  FAILED  ] memory_pool.shared_mem_pool_same_topology_twice_weights
> 
>  8 FAILED TESTS
>   YOU HAVE 17245 DISABLED TESTS
> 
> tests/CMakeFiles/tests.dir/build.make:867: recipe for target 'build/out/Linux64/Debug/tests64' failed
> make[3]: *** [build/out/Linux64/Debug/tests64] Error 1
> make[3]: *** Deleting file 'build/out/Linux64/Debug/tests64'
> CMakeFiles/Makefile2:202: recipe for target 'tests/CMakeFiles/tests.dir/all' failed
> make[2]: *** [tests/CMakeFiles/tests.dir/all] Error 2
> CMakeFiles/Makefile2:214: recipe for target 'tests/CMakeFiles/tests.dir/rule' failed
> make[1]: *** [tests/CMakeFiles/tests.dir/rule] Error 2
> Makefile:190: recipe for target 'tests' failed
> make: *** [tests] Error 2
>

**Comment by tponieck** [comment]
Hi,
It looks like driver issue. Please update your driver from:
https://downloadcenter.intel.com/download/27988/Intel-Graphics-Driver-for-Windows-10?v=t

**Comment by tponieck** [comment]
Linux driver location:
https://github.com/intel/compute-runtime/releases

**Comment by smit411** [comment]
Thank you tponieck for quick response.
I update drivers from the link you provided, and repeat whole the procedure.
But, again I got the same issue.

**Comment by tponieck** [comment]
Could you share your platform device id?

**Comment by tponieck** [comment]
Ubuntu?

**Comment by smit411** [comment]
Yes, Ubuntu 16.04.5. kernel version 4.7

**Comment by tponieck** [comment]
Hi Smit411
I am not able to reproduce your issue. Does it occur on debug setup only? can you share full output log?

**Comment by smit411** [comment]
Hello tponieck,
Yesterday while I was installing OpenVINO to my system, I upgrade my kernel version to 4.17 as per requirement and downgrade cmake ver from 3.12 to 3.9.2. And after that, don't know how but now I'm able to build "tests" and "tutorial".
